name: Web & iOS build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  probe-ios:
    name: Probe iOS folder
    runs-on: ubuntu-latest
    outputs:
      has_ios: ${{ steps.check.outputs.has_ios }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if ios/ exists
        id: check
        shell: bash
        run: |
          if [ -d "ios" ]; then
            echo "has_ios=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_ios=false" >> "$GITHUB_OUTPUT"
          fi

  web-build:
    name: Build Web (Vite)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm build
          else
            npm run build
          fi

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist
          if-no-files-found: error

  ios-ipa:
    name: Build iOS IPA (if ios/ exists)
    needs: [probe-ios]
    if: ${{ needs.probe-ios.outputs.has_ios == 'true' }}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci
          else:
            npm install
          fi

      - name: Build web for iOS container
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm build
          else:
            npm run build
          fi

      - name: Sync Capacitor (optional)
        run: |
          if [ -f node_modules/.bin/cap ]; then
            npx cap sync ios
          fi

      - name: Build iOS (unsigned if possible)
        shell: bash
        run: |
          if [ -d "ios/App" ] && [ -f "ios/App/App.xcworkspace/contents.xcworkspacedata" ]; then
            xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release -sdk iphoneos -archivePath "$PWD/build/App.xcarchive" archive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
            xcodebuild -exportArchive -archivePath "$PWD/build/App.xcarchive" -exportPath "$PWD/build" -exportOptionsPlist ios/exportOptions.plist || true
          elif [ -d "ios" ]; then
            # Fallback: try to find a workspace or project automatically
            WS=$(ls ios/*.xcworkspace 2>/dev/null | head -n1 || true)
            PROJ=$(ls ios/*.xcodeproj 2>/dev/null | head -n1 || true)
            if [ -n "$WS" ]; then
              SCHEME=$(xcodebuild -workspace "$WS" -list -json | /usr/bin/python3 - <<'PY'
import json,sys
j=json.load(sys.stdin)
print(j["workspace"]["schemes"][0] if j.get("workspace",{}).get("schemes") else "")
PY
)
              if [ -n "$SCHEME" ]; then
                xcodebuild -workspace "$WS" -scheme "$SCHEME" -configuration Release -sdk iphoneos -archivePath "$PWD/build/App.xcarchive" archive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO || true
                xcodebuild -exportArchive -archivePath "$PWD/build/App.xcarchive" -exportPath "$PWD/build" -exportOptionsPlist ios/exportOptions.plist || true
              fi
            elif [ -n "$PROJ" ]; then
              SCHEME=$(xcodebuild -project "$PROJ" -list -json | /usr/bin/python3 - <<'PY'
import json,sys
j=json.load(sys.stdin)
t=list(j.get("project",{}).get("targets",[]))
print(t[0] if t else "")
PY
)
              if [ -n "$SCHEME" ]; then
                xcodebuild -project "$PROJ" -scheme "$SCHEME" -configuration Release -sdk iphoneos -archivePath "$PWD/build/App.xcarchive" archive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO || true
                xcodebuild -exportArchive -archivePath "$PWD/build/App.xcarchive" -exportPath "$PWD/build" -exportOptionsPlist ios/exportOptions.plist || true
              fi
            else
              echo "Found ios/ but no Xcode workspace/project. Skipping build."
            fi
          else
            echo "ios/ directory missing; skipping Xcode build."
          fi

      - name: Upload IPA (if present)
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: |
            build/*.ipa
            build/**/*.ipa
          if-no-files-found: warn

  ios-skip-notice:
    name: Skip iOS (no ios/ folder)
    needs: [probe-ios]
    if: ${{ needs.probe-ios.outputs.has_ios != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "No ios/ folder found. Skipping iOS IPA build."
