name: Web & iOS build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  probe-ios:
    name: Probe iOS folder
    runs-on: ubuntu-latest
    outputs:
      has_ios: ${{ steps.check.outputs.has_ios }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if ios/ exists
        id: check
        shell: bash
        run: |
          if [ -d "ios" ]; then
            echo "has_ios=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_ios=false" >> "$GITHUB_OUTPUT"
          fi

  web-build:
    name: Build Web (Vite-only) + diagnostics
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        shell: bash
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci
          else:
            npm install
          fi

      - name: Build (vite only)
        shell: bash
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm exec vite build
          else
            npx vite build
          fi

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist
          if-no-files-found: error

  ios-ipa:
    name: Build unsigned .ipa (if ios/ exists)
    needs: [probe-ios, web-build]
    if: ${{ needs.probe-ios.outputs.has_ios == 'true' }}
    runs-on: macos-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        shell: bash
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci
          else:
            npm install
          fi

      - name: Build web for iOS container (vite only)
        shell: bash
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm exec vite build
          else
            npx vite build
          fi

      - name: Sync Capacitor (optional)
        shell: bash
        run: |
          if [ -f node_modules/.bin/cap ]; then
            npx cap sync ios
          else
            echo "Capacitor CLI not found, skipping cap sync."
          fi

      - name: Archive with xcodebuild (unsigned)
        shell: bash
        run: |
          set -e
          if [ -d "ios/App" ] && [ -d "ios/App/App.xcworkspace" ]; then
            xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release -sdk iphoneos -archivePath "$PWD/build/App.xcarchive" archive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
          else
            echo "No standard Capacitor workspace found under ios/App. Listing ios/: "
            ls -la ios || true
            exit 1
          fi

      - name: Try exportArchive (may fail without signing)
        shell: bash
        continue-on-error: true
        run: |
          if [ -d "$PWD/build/App.xcarchive" ]; then
            xcodebuild -exportArchive -archivePath "$PWD/build/App.xcarchive" -exportPath "$PWD/build" -exportOptionsPlist ios/exportOptions.plist
          fi

      - name: Fallback: zip .app into .ipa (unsigned)
        shell: bash
        run: |
          set -e
          APPDIR="$PWD/build/App.xcarchive/Products/Applications"
          APP=$(ls "$APPDIR"/*.app 2>/dev/null | head -n1 || true)
          if [ -z "$APP" ]; then
            echo "No .app found in archive. Aborting."
            exit 1
          fi
          mkdir -p "$PWD/build/Payload"
          cp -R "$APP" "$PWD/build/Payload/App.app"
          cd "$PWD/build"
          /usr/bin/zip -qry "GiannicorpGym-unsigned.ipa" Payload
          echo "Created unsigned IPA at $PWD/build/GiannicorpGym-unsigned.ipa"

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: |
            build/*.ipa
            build/**/*.ipa
          if-no-files-found: error

  ios-skip-notice:
    name: Skip iOS (no ios/ folder)
    needs: [probe-ios]
    if: ${{ needs.probe-ios.outputs.has_ios != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "No ios/ folder found. Skipping iOS IPA build."
